<!DOCTYPE html>
<html lang="en" debug="true" >
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Project Nidus</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="css/_3rdparty.obsolete.css" rel="stylesheet">
    <link href="css/full-slider.css" rel="stylesheet">

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script type="text/javascript" src="js/_3rdparty.js"></script> -->
    <!-- <script type="text/javascript" src="js/code_phoenix.js"></script> -->
    <!-- <script type="text/javascript" src="js/main.js"></script> -->
    <!-- <script type="text/javascript" src='<phx:echo var="hostname" />/js/ladmin.js'></script> -->
    <script type="text/javascript" 
            data-depends="/js/_3rdparty.obsolete.js" 
            data-sources="js/nidus.js"
            src="/phink.js">
    </script>
</head>
<body data-twttr-rendered="true" data-spy="scroll" >
    <div id='body'></div>
    <!-- <script type="text/javascript" src="js/debug.js"></script> -->
</body>
</html>